name: anarchist
description: "An unofficial AniList mobile app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  cached_network_image: ^3.4.1
  catppuccin_flutter: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.3.0
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
