// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG850GL11FfaJDOKDA9aU-FVFdvma2lT0',
    appId: '1:465019105822:android:0c57b6bdadad6409ecf40f',
    messagingSenderId: '465019105822',
    projectId: 'al-anarchist',
    storageBucket: 'al-anarchist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj0StARhMBchdd4tWjVLVEuKrpRwOA2Vg',
    appId: '1:465019105822:ios:48ce9bd9563314a4ecf40f',
    messagingSenderId: '465019105822',
    projectId: 'al-anarchist',
    storageBucket: 'al-anarchist.firebasestorage.app',
    iosBundleId: 'world.snows.anarchist',
  );
}
