name: Flutter

on: [ push, pull_request ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter analyze

  build:
    needs: setup
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build apk
      - run: flutter build appbundle