name: Flutter

on:
  push:
    paths:
      - 'lib/**'
      - 'android/**'
      - 'ios/**'
  pull_request:
    paths:
      - 'lib/**'
      - 'android/**'
      - 'ios/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter analyze

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: flutter build apk
