name: Flutter

on: [ push, pull_request ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: flutter analyze

  build:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.ref == "refs/heads/master" }}
    steps:
      - run: flutter build apk
      - run: flutter build appbundle